services:
  - type: web
    name: delcampo
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: "Del Campo"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "true"
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d50e5875r7bs739c7mlg-a
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: database_j5yk
      - key: DB_USERNAME
        value: user
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_DRIVER
        value: file
